services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'biztravel360'
      MYSQL_USER: 'biztravel'
      MYSQL_PASSWORD: 'biztravel'
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - './db-data:/var/lib/mysql'
    ports:
      - 3306:3306